/*
 * File: leg_spd.c
 *
 * MATLAB Coder version            : 5.5
 * C/C++ source code generated on  : 04-Jun-2024 22:21:12
 */

/* Include Files */
#include "rm_chassis_controllers/vmc/leg_spd.h"
#include <math.h>

/* Function Definitions */
/*
 * LEG_SPD
 *     SPD = LEG_SPD(DPHI1,DPHI4,PHI1,PHI4)
 *
 * Arguments    : double dphi1
 *                double dphi4
 *                double phi1
 *                double phi4
 *                double spd[2]
 * Return Type  : void
 */
void leg_spd(double dphi1, double dphi4, double phi1, double phi4, double spd[2])
{
  double t11;
  double t12;
  double t14;
  double t15;
  double t19;
  double t2;
  double t21;
  double t23;
  double t25;
  double t3;
  double t35;
  double t38;
  double t4;
  double t5;
  double t51;
  double t6;
  double t61;
  double t62;
  double t63;
  double t7;
  double t8;
  double t9;
  /*     This function was generated by the Symbolic Math Toolbox version 9.2.
   */
  /*     04-Jun-2024 22:11:45 */
  t2 = cos(phi1);
  t3 = cos(phi4);
  t4 = sin(phi1);
  t5 = sin(phi4);
  t6 = t2 * 0.14;
  t7 = t3 * 0.14;
  t8 = t4 * 0.14;
  t9 = t5 * 0.14;
  t11 = t2 * 0.07;
  t12 = t3 * 0.07;
  t14 = t4 * 0.07;
  t15 = t5 * 0.07;
  t19 = t8 - t9;
  t21 = t14 - t15;
  t23 = (t7 - t6) + 0.12;
  t25 = (t12 - t11) + 0.06;
  t35 = t19 * t19 + t23 * t23;
  t38 = t2 * t19 * 0.28 + t4 * t23 * 0.28;
  t3 = t3 * t19 * 0.28 + t5 * t23 * 0.28;
  t19 = 1.0 / (t25 + t35);
  t23 = t19 * t19;
  t5 = sqrt((t21 * t21 + t25 * t25) - t35 * t35);
  t51 = 1.0 / t5;
  t4 = (t15 - t14) + t5;
  t2 = atan(t19 * t4) * 2.0;
  t61 = cos(t2);
  t62 = sin(t2);
  t63 = 1.0 / (t23 * (t4 * t4) + 1.0);
  t5 = (t14 + t38) * t23 * t4 + t19 * (t11 - t51 * ((t6 * t21 + t8 * t25) - t35 * t38 * 2.0) / 2.0);
  t38 = (t15 + t3) * t23 * t4 + t19 * (t12 - t51 * ((t7 * t21 + t9 * t25) - t35 * t3 * 2.0) / 2.0);
  t11 = t8 + t62 / 4.0;
  t14 = (t6 + t61 / 4.0) - 0.06;
  t2 = t11 * t11;
  t7 = 1.0 / t11;
  t23 = t14 * t14;
  t9 = 1.0 / t2;
  t51 = t61 * t63;
  t19 = t6 - t51 * t5 / 2.0;
  t3 = t62 * t63;
  t5 = t8 - t3 * t5 / 2.0;
  t4 = 1.0 / sqrt(t2 + t23);
  t2 = 1.0 / (t9 * t23 + 1.0);
  spd[0] =
      dphi1 * t4 * (t11 * t19 * 2.0 - t14 * t5 * 2.0) / 2.0 + dphi4 * t4 * (t51 * t11 * t38 - t3 * t14 * t38) / 2.0;
  spd[1] = dphi4 * t2 * (t3 * t7 * t38 / 2.0 + t51 * t9 * t14 * t38 / 2.0) + dphi1 * t2 * (t7 * t5 + t9 * t14 * t19);
}

/*
 * File trailer for leg_spd.c
 *
 * [EOF]
 */
