/*
 * File: leg_pos.c
 *
 * MATLAB Coder version            : 5.5
 * C/C++ source code generated on  : 04-Jun-2024 22:15:34
 */

/* Include Files */
#include "rm_chassis_controllers/vmc/leg_pos.h"
#include <math.h>

/* Function Definitions */
/*
 * LEG_POS
 *     POS = LEG_POS(PHI1,PHI4)
 *
 * Arguments    : double phi1
 *                double phi4
 *                double pos[2]
 * Return Type  : void
 */
void leg_pos(double phi1, double phi4, double pos[2])
{
  double a;
  double b_a;
  double t14;
  double t15;
  double t2;
  double t3;
  double t4;
  double t5;
  double t6;
  double t8;
  /*     This function was generated by the Symbolic Math Toolbox version 9.2.
   */
  /*     04-Jun-2024 22:11:44 */
  t2 = cos(phi1);
  t3 = cos(phi4);
  t4 = sin(phi1);
  t5 = sin(phi4);
  t6 = t2 * 0.14;
  t8 = t4 * 0.14;
  t14 = t4 * 0.07;
  t15 = t5 * 0.07;
  t5 = t8 - t5 * 0.14;
  a = t14 - t15;
  b_a = (t3 * 0.14 - t6) + 0.12;
  t4 = (t3 * 0.07 - t2 * 0.07) + 0.06;
  t5 = t5 * t5 + b_a * b_a;
  t4 = atan(1.0 / (t4 + t5) * ((t15 - t14) + sqrt((a * a + t4 * t4) - t5 * t5))) * 2.0;
  t5 = t8 + sin(t4) / 4.0;
  t4 = (t6 + cos(t4) / 4.0) - 0.06;
  pos[0] = sqrt(t5 * t5 + t4 * t4);
  pos[1] = -atan(t4 / t5);
}

/*
 * File trailer for leg_pos.c
 *
 * [EOF]
 */
